pipeline {
  agent any
  tools { nodejs 'node18' } 
  environment {
    NAMESPACE = "apps"
    CHART     = "charts/app-chart"
    IMAGE     = "backend:local"
    PORT      = "3001"
    CI        = 'true'
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Backend tests') {
      steps {
        dir('backend') {
          sh '''
            set -eux
            if [ -f package-lock.json ]; then npm ci; else npm install; fi
            npm test -- --ci
          '''
        }
      }
    }

    stage('Install helm/kubectl') {
      steps {
        sh '''
          set -eux
          mkdir -p "$HOME/bin"
          export PATH="$HOME/bin:$PATH"

          # Install kubectl if missing
          if ! command -v kubectl >/dev/null; then
            KUBECTL_VERSION="v1.33.1"
            curl -fsSL -o "$HOME/bin/kubectl" "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
            chmod +x "$HOME/bin/kubectl"
          fi

          # Install helm if missing
          if ! command -v helm >/dev/null; then
            export HELM_VERSION="v3.18.4"
            curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 \
            | USE_SUDO=false HELM_INSTALL_DIR=$HOME/bin bash
          fi

          helm version
          kubectl version --client

        '''
      }
    }

    stage('Deploy via Helm') {
      steps {
        sh '''
          set -eux
          kubectl get ns ${NAMESPACE} || kubectl create ns ${NAMESPACE}
          helm upgrade --install backend ${CHART} \
            -n ${NAMESPACE} \
            --reset-values \
            -f "$CHART"/values-backend.yaml \
            --wait --timeout 10m --debug
        '''
      }
    }
  }

  post {
    always {
      sh 'kubectl -n ${NAMESPACE} get all || true'
    }
  }
}
